<?php

namespace App\Models;

use Illuminate\Support\Str;

trait Uuid
{
    protected static function boot(): void
    {
        parent::boot();
        static::creating(function ($model) {
            if (!$model->getKey()) {
                $model->{$model->getKeyName()} = (string) Str::uuid();
            }
        });
    }

    public function getIncrementing()
    {
        return false; // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function getKeyType(): string
    {
        return 'string';
    }
}
